### ISSUE TITLE
fix deprecation warnings in Node 8

### ISSUE THREAD

**Issue by vigneshshanmugam** [zalando/tailor#149]
Node 8 provides deprecation warnings when running with --pending-deprecation flag and we need small fixes in tailor core. 

 + [ ] Move from Buffer() to Buffer.allocUnsafe (https://nodejs.org/en/blog/release/v8.0.0/#buffer-changes)
 + [ ] Include Node 8 as part of travis build

**Comment by addityasingh** [comment]
@vigneshshanmugam IMO we should use `Buffer.allocUnsafe()` instead of `Buffer.alloc()` to gain some performance in memory allocation. Ideally, we can create some benchmark tests to compare these 2, but I think Tailor doesn't have scenarios where memory leak can happen because of Buffer.allocUnsafe()`. Thoughts?

**Comment by vigneshshanmugam** [comment]
Memory leak can happen in tailor due to number of subscribers to tailor's event emitters. This might be a hint.
