### ISSUE TITLE
To use 'Promisify' to simplify the code

### ISSUE THREAD

**Issue by luizdesign** [zalando/tailor#172]
Continue the discuss about use promisify started in #171 (https://github.com/zalando/tailor/pull/171#issuecomment-324324643)

**Comment by addityasingh** [comment]
@vigneshshanmugam Based on our discussion earlier on the PR for this issue [here](https://github.com/zalando/tailor/pull/157), I remember that the `util.promisify` library had some performance issue because of prototype chaining. Do you think it still makes sense to https://github.com/ljharb/util.promisify library?

**Comment by vigneshshanmugam** [comment]
@addityasingh Lets reopen the PR and add the remaining changes if you are interested in taking it forward. Most projects are using it these days.

**Comment by addityasingh** [comment]
@luizdesign If you want to work on it, please go ahead. Else, I can take it up

**Comment by addityasingh** [comment]
Duplicate of https://github.com/zalando/tailor/issues/153

**Comment by luizdesign** [comment]
@addityasingh  I didn't start work on it yet, I'm working to finish the changes to #171

**Comment by addityasingh** [comment]
Cool. Let me make the changes quickly then

**Comment by vigneshshanmugam** [comment]
You guys wanna take it up?

**Comment by addityasingh** [comment]
@vigneshshanmugam Please have a look now
