### ISSUE TITLE
How to organize templates?

### ISSUE THREAD

**Issue by kevinsimper** [zalando/tailor#189]
I am little unsure on how to organize templates in regards to redirects.

If you had a webshop you would have a template called `product` and `list`, but your users would obviously not access `/product` and `/list`.

One easy solution would be to rewrite `req.url` on the request object to map `/blue-widget/` to `/product`?

**Comment by vigneshshanmugam** [comment]
We use https://github.com/zalando/skipper as a router in front of tailor at Zalando, So the request path is rewritten to make sure we hit the template for a particular page pattern 

```
Routing 

Host("www.example.com") && Path("/product-page/*") 
-> setPath("/product-template")
-> tailor endpoint
```

For the above url pattern, the template `prodcuct-template` would be picked and tailor would be completely unaware of the requested url. The original request URI would be passed as a Header to tailor to continue passing it to the other fragments in the request pipeline. 

You can also do the same thing using a middleware in front of tailor to do the same instead of skipper.

**Comment by kevinsimper** [comment]
Thank you @vigneshshanmugam, had not seen it together with skipper, makes a lot of sense! 👍

**Comment by kevinsimper** [comment]
I have been doing something like this, wants to share this with others because I feel this is the missing link to understand and use it with ease.

There isn't a common path for passing down the `originalUrl` to the fragments and only 3 headers are not removed by default

https://github.com/zalando/tailor/blame/master/lib/filter-headers.js#L2


```
http
    .createServer((req, res) => {
        if (req.url === '/favicon.ico') {
            res.writeHead(200, { 'Content-Type': 'image/x-icon' });
            return res.end('');
        }

        // ADDED referer
        req.headers['referer'] = req.url
        req.url = '/index'
       // END
        tailor.requestHandler(req, res);
    })
    .listen(8080, function() {
        console.log('Tailor server listening on port 8080');
    });
```

**Comment by DeTeam** [comment]
@kevinsimper using referer for such purpose might be a bad idea, since it can be later needed for various SEO/marketing-related logic inside your fragment/other backends.

What you can do, though, is to provide your own filter headers function and use some custom header to carry the original url (that's what we do with tailor).

Look for ["filterRequestHeaders"](https://github.com/zalando/tailor#options).

**Comment by kevinsimper** [comment]
@DeTeam Yeah I looked at that function and I did use originally something like `original-url` but saw I had to make my own function to have the URL passed down.

Couldn't there be a default header that isn't removed by default?  It would make it easier for people to adopt Tailor with easier defaults.

**Comment by DeTeam** [comment]
@kevinsimper good suggestion!

I'll try to find some time and add it to tailor (would need to align with the team first)

**Comment by DeTeam** [comment]
@kevinsimper sorry, took a bit of time, but here's what we can do:

Add two more headers `x-request-uri` & `x-request-host` to the list + adjust README with the info we gathered here so that other people don't get confused.

Do you want to contribute with a PR? ;)

**Comment by kevinsimper** [comment]
@DeTeam I gave it a shot hehe 😄 https://github.com/zalando/tailor/pull/192

**Comment by DeTeam** [comment]
Thank you, @kevinsimper, merged!

**Comment by DeTeam** [comment]
Released in https://github.com/zalando/tailor/releases/tag/3.4.0, published on npm.
