### ISSUE TITLE
How to properly handle dependencies

### ISSUE THREAD

**Issue by tsnolan23** [zalando/tailor#196]
Sorry if this isn't the place to ask this, I know it isn't actually an issue, but I couldn't find anywhere else to ask it or find information on it.   

**What is the proper/recommended way of handling dependencies within a template between different fragments?**

I've watched most of the Mosaic presentations for Zalando employees, but I'm struggling to see how allowing each team to choose their own stack doesn't lead to dependency overload and poor performance with this architecture.  For example, say I have 4 fragments composing a template. Two of them use the same version of React, one uses Vue, and another uses an older version of React. 

Based on the described architecture, the above scenario isn't exactly far-fetched - teams choose their stack and may be using different versions of the same library, so how do you prevent the browser from needing to load 2 different versions of React and Vue from the client-side?  

Is the idea that you should always "try" to be consistent with the stack, unless otherwise necessary? Mixing stacks at any level require all those dependencies to be run in the browser which means based on the template, you may be loading several MVC frameworks just to support each individual fragment.

I saw a thread (#160) that mentioned that you use RequireJS internally for managing the dependencies, so do you just require everyone that uses React to use the same version?

I'm also struggling to see how that method aligns to the architecture because in one of the lectures it was mentioned that the team that owns the template, doesn't need to own the fragment and vice-versa, so how would a team know which dependencies to include if it's not included in the bundle?

I've just started playing around with this architecture, so sorry if this is listed somewhere, but I'm excited to try and build a prototype, but running into some of the above and would welcome any information you could provide!

If there is a more proper location to discuss this outside of the GitHub issues, I'd more than happy to move it there.

**Comment by mo-gr** [comment]
This is absolutely the right place to ask.

**Comment by mo-gr** [comment]
When we created mosaic, we tried very hard to keep it agnostic of specific frontend frameworks. But the reality of using mosaic is, that a mosaic installation will very likely dictate a dominant framework. In our case, we highly recommend to the teams to use react and we have a fragment in every base template in tailor, that provides a small environment, that the fragments are allowed to rely on. In our case, those are some polyfills, a communication bus and a clearly defined version of React.

In general, nothing stops a fragment from bundling their own version of angular or similar. But in our opinion, there is very little value in having multiple big frameworks on the same page at the same time. So we strongly discourage it.

So your understanding is correct, every fragment just bundles whatever it needs in its fragment script and purely by convention, we discourage teams from using big/heavy frameworks or libraries, that fail if they are included on the same page twice.

We have looked into bundling more common libraries automatically based on the fragments on a page, but ultimately decided against it - more optimising towards the “warm-cache”. In automatic bundling of common libraries, we would have to deal with potentially painful library updates as well as invalidating caches whenever a single fragment gets redeployed.

So in your case: if you have some fragments, that want to use vue instead of react, just let them bundle it. And provide, whatever you decide as your major-framework as part of the global environment before other fragments load.

**Comment by vigneshshanmugam** [comment]
In addition to what @mo-gr explained, We have a base fragment on every template(Pages) that has set of common libraries and polyfills that are exposed as modules via RequireJs. The modules in the base fragments are nothing but the libraries that are used on more than two fragments on the page. 

In our case, Since we use React on most of the fragments. It is added as part of the common bundle and fragment uses React as a dependency which is handled via RequireJS on the page. An example of fragment using `react` and `webpack` would simply list `react` as [externals](https://webpack.js.org/configuration/externals/) which excludes the `react` dependency from fragment bundle since we have react available as a common bundle on the page 

If any another fragment would want to use Angular, Vue etc. They would need to simply bundle that code and handle the dependencies chain. 

We also make sure that the libraries present in the common bundle stays minimal to keep our performance budget under control.

**Comment by tsnolan23** [comment]
@vigneshshanmugam @mo-gr Thanks for the response, that makes sense.  We're going to try to implement something similar by bundling common libraries in a fragment. Would you happen to have an example of the fragment that just contains the common bundle? I'd be curious to see your implementation.

Also, I assume that the fragment that provides the bundle has no other purpose? Meaning, its sole job is to serve up that bundle and doesn't return any HTML or content that is actually rendered to the page.

**Comment by tsnolan23** [comment]
The biggest issue I'm having with the common bundle fragment is exposing the React library as a global for the other fragments to utilize.  

* Each of the fragments that require React list it as an external in their webpack config, so it's not included with each.
* The common fragment contains React and ReactDOM in the bundle provided in the header.  

I suppose at that point it's more of a Webpack question, but the relationship between the common bundle fragment's webpack config and the dependent fragment's webpack config is where I cannot get it to function. Do you happen to have an example of those?

**Comment by vigneshshanmugam** [comment]
> The biggest issue I'm having with the common bundle fragment is exposing the React library as a global for the other fragments to utilize.

Yeah thats where RequireJS or any other module system comes in, The base fragment in our case includes react and other libraries which is exposed as a AMD bundle by this way

```js
define('react', function() {/* react code */})
```

The fragment JS bundle would then simply need to inform that react is a dependency for it. This can be achieved with help of Webpack or other module bundlers where you can specify as externals. The code then would simply look like this

```js
define(['react'], function(reactModule) {
  // Your fragment JS code goes here
}); 
```

By this way, All the script loading becomes asynchronous and dependency management is handled properly. I do not have a sample repo but you can check how it is used in the examples. 

Acting like base 
https://github.com/zalando/tailor/blob/eb8428fcf57e3724f4691ea3bd62808b5f5a67d5/examples/multiple-fragments-with-custom-amd/templates/base-template.html#L10

From Fragment
https://github.com/zalando/tailor/blob/eb8428fcf57e3724f4691ea3bd62808b5f5a67d5/examples/multiple-fragments-with-custom-amd/fragment.js#L10

**Comment by tsnolan23** [comment]
@vigneshshanmugam Thanks, out of curiosity, are you using webpack to bundle the common dependencies or another tool?

I see this code on the Zalando site which seems to loop over the bundle and define dependencies from it, so I was curious what tool you used to create that bundle?

```
(function(d) {
    require.config({
        waitSeconds: 0,
        onNodeCreated: function(node) {
            node.crossOrigin = "anonymous"
        }
    });
    require(d);
    define('z-shop-js-env', d);
    var arr = ['safe-fetch', 'react', 'react-dom', 'react-addons-css-transition-group', 'z-shop-ui', 'z-shop-event-bus', 'tranzlate', 'classnames'];
    while (i = arr.pop())(function(dep) {
        define(dep, d, function(b) {
            return b[dep];
        })
    })(i);
}(['https://mosaic01.ztat.net/base-assets/3-0-6/assets/bundle.js']));
```

**Comment by tsnolan23** [comment]
@vigneshshanmugam @mo-gr I did create a repo that goes a bit more in-depth with the shared dependency usage with Tailor. You can check it out here if you'd like:

https://github.com/tsnolan23/mosaic-tailor-react-example

I think it may be useful for anyone attempting to do the same thing.

**Comment by vigneshshanmugam** [comment]
> I see this code on the Zalando site which seems to loop over the bundle and define dependencies from it, so I was curious what tool you used to create that bundle?

We have the bundle generated by webpack which is https://mosaic01.ztat.net/base-assets/3-0-6/assets/bundle.js. We do not have any tool for generating that, but a simple script that defines all of the dependencies in the above bundle and exposes them in the module chain so fragment code can simply do this on the page
```js
define('fragment-1', ['react'], () => // fragment code)
```

> I did create a repo that goes a bit more in-depth with the shared dependency usage with Tailor. You can check it out here if you'd like:

Awesome job, Thanks a lot. I will have a look. We can also add that to the readme of tailor. If you are interested in giving a PR, Please go ahead :)

**Comment by vigneshshanmugam** [comment]
Closing this as all questions are addressed.
