### ISSUE TITLE
Allow default values for fragment attributes

### ISSUE THREAD

**Issue by dami-gg** [zalando/tailor#211]
It would be useful, in some cases, to add a configuration option to allow setting default values for all the attributes of the fragments.

Currently, when getting the attributes on fragment creation, a default value for _timeout_ is set. However, this is not possible for other attributes such as for example _fallback-src_

We consider a situation where we would need to provide our own error handling fragment as a fallback, to be used in case the fragments do not specify their own one (most likely situation).

A possible solution we see for this would be to specify a default value which will be used just when we identify no value has been set for that attribute in the fragment itself.

These default values could be also set specifically per fragment, instead of globally. This would give even more configuration flexibility, but perhaps it is overengineering at this point. 

This feature will allow making Tailor more configurable especially after the flexibility that the recently merged feature (#207) to allow custom attributes provides.

Before I open a pull request, I would like to get some feedback from the maintainers on this idea.

**Comment by vigneshshanmugam** [comment]
> Currently, when getting the attributes on fragment creation, a default value for timeout is set. However, this is not possible for other attributes such as for example fallback-src

The default value is set for most of the attributes like async, primary, public and timeout. We choose not to default values for src and fallback-src since its a over kill. 

> We consider a situation where we would need to provide our own error handling fragment as a fallback, to be used in case the fragments do not specify their own one (most likely situation).

This is really a bad idea, If two of the fragments on the page fail, You dont want to show the same error message at multiple places on the same page. This is why we dont support default values for fallback-src. It should be explicit for each and every fragment and mostly in our current implementation in Zalando, we use a static cache when fragments fail. 

If you still believe its needed, You can do it by passing your own `requestFragment` function which takes in fragment attributes and overrides based on some other heuristics.

**Comment by dami-gg** [comment]
I see your point.

I'm not really sure we can just enforce a rule in our portal context so that all the fragments provide a fallback-src but I will try your suggestion using a custom requestFragment and see what I can come up with.

Thanks for your explanation!
