### ISSUE TITLE
SPA and WebForms Applications

### ISSUE THREAD

**Issue by robertomellocampos** [zalando/tailor#240]
Hello,

I would like to put at the same canvas, many web applications with many different tecnologies and my main concern is about how can I manage the fragment assets.

Whether Tailor uses AMD to get the fragment content, my fragment can start some script before their dependency to be loaded. For exemple if I have Some script and link tags inside of the fragment.

How can I control this flux?

Best Regards,

**Comment by vigneshshanmugam** [comment]
The best way is to do the dependency management in your fragment since you know which scripts are dependent on each other.

```js
define("react", function() {});

require(["react", /** extra libs **/], () => {
   // fragment app code goes here
})
```
You can send this JS via fragment link header or put in script tag. It should not matter. 

Incase if you want this behaviour for every fragment in the page, the best way is to put the libs on HTML templates and send the scripts through fragment link tags.
