### ISSUE TITLE
Tailor and next.js

### ISSUE THREAD

**Issue by smirnowld** [zalando/tailor#266]
Is it possible to use Tailor with next.js? From what I see, both Tailor and next.js insist on using their own request handlers, which interfere with one another and I wasn't able to find a way to get the two to respect each other.

**Comment by smirnowld** [comment]
I managed to hack around it by first rendering the page with next.js, and passing the resulting page (with fragment placeholders) to Tailor. This means I'm going through two render stages, which doesn't exactly sound great (and I'm not sure yet if it actually means I'm losing in terms of performance) - would be good to have a more elegant solution.

**Comment by arhont375** [comment]
Tailor does not perform any SSR rendering (just stream content from your fragments), so if you want to use Tailor with any SSR rendering then it means that you need to render your fragment before it will go to Tailor.

In general if you want to use Tailor with SSR I think it's better to have `template.html` with `fragment`'s tags. This tags will be replaced by your prerendered fragments. In that case page will be actually composed from different prerendered fragments. 

On the other side if it's really needed for you to render part of the page and this rendered page must include `fragment` tags to resolve other parts, then your approach probably correct. But you should check that react will not rerender whole page on client side because DOM structure is different.

**Comment by kirankalyan5** [comment]
@smirnowld - I'm interested to hear your outcome. Did you want to wrap your `next js` app as the fragment in the `tailor js` template?

If yes, then did you manage to achieve it, I would like to hear the consequences.

Thanks in advance.

**Comment by smirnowld** [comment]
Sorry @kirankalyan5 , it was too long ago to remember, and I've not touched either Tailor or NextJS for over a year, so I can't help you.
