### ISSUE TITLE
Recommendations for local development

### ISSUE THREAD

**Issue by tobsch** [zalando/tailor#275]
Hi guys,

just wanted to ask how you use tailor in your local setups or what you would recommend?
We're using docker-compose and have multiple projects. One "Monolith" that also contains header & footer and a few new SPAs that are let's say "more elegant".

Is there any idea on how to structure things?
We are a small company, so the setup that you running is - I guess - not an option.
Would you recommend having a central repo with layouts, a docker-compose file and skipper & tailor running and separate repos with the single projects?
How would the "layout repo" interact with the rest?

Maybe there is a good tutorial we missed for "smaller setups"?

Thanks

**Comment by vigneshshanmugam** [comment]
Before I begin to recommend something, I am not sure if you have already seen this playground repo. 

https://github.com/mosaic9/mosaic-compose

/cc @aryszka

**Comment by tobsch** [comment]
Thanks, that already helps.
We had a similar setup in a separate repo.
Let's be a bit more concrete:
header and footer live in online version of the website, body part is in your local app. 
Would you then setup a local version of that app with tailor living inside the apps repo?
Or how would you structure it?

**Comment by vigneshshanmugam** [comment]
If you are the one maintaining both tailor and the body part of the application, then
+ In your local tailor repo, Create a template pointing to real version of the header and footer and local version of your app
```html
<body>
   <fragment src="header.live.com" id="header"/> 
    
   <!-- your local application server -->
   <fragment src="localhost:8200/my-app-server.js" id="local-app" />
   
   <fragment src="footer.live.com" id="footer"/> 
</body>
```

If you are not controlling tailor server and only in control of your application, We developed something called portal-gun (which is not open sourced yet) to replace the live application server with your local application server. Its basically a proxy between tailor and your server. 

Since you are working in Zalando, Please ask the team maintaining tailor to help you out.
