### ISSUE TITLE
Tailor fragments in Vue.js / fragments cascades

### ISSUE THREAD

**Issue by JohnOllhorn** [zalando/tailor#286]
That could very well be a Vuejs question, but I'd like to try:

Is it possible to include a fragment in a Vue.js app?
With the pure HTML template you can only include fragments among each other.
But I would like to embed fragments depending on the route or other conditions that provide vuejs.

If this is not possible: Are there examples of Tailor in conjunction with ejs, or other template engines? That would be a bit more dynamic.

Many thanks for your work

**Comment by vigneshshanmugam** [comment]
> Is it possible to include a fragment in a Vue.js app?

Yes its totally possible, But it has huge performance since it incurs additional roundtrip since we have to now go fetch the fragment after fetching the Vue app itself. Have a look at the test where we inject multiple fragment urls from remote app (can be vue or anything) and then we have to manually create a stream that handles the response from those endpoints. These are all handled via special tags

```html
// In page template
<remote-vue src="http://get-me-the-app:3000"/>
```
```js
// tailor options
new Tailor({
  handleTags: ['fragment', 'remote-vue'],
  handleTag: handleRemoteTag,
});

function handleRemoteTag(tag) {
   if(tag.name === "remote-vue") {
     // fetch the stream
     // parse the response for fragment attributes
    // return the stream
   }
}
```
Check this example . -https://github.com/zalando/tailor/blob/master/tests/process-template.js#L50

If you need dynamic temples based on a route, I would suggest to use a template storage backend and not rely on File system that is enabled by default in tailor. What you could do is modify the fetchTemplate function in tailor 

```js
async function fetchTemplate(path) {
  // path would be like /index, /route etc

  const templateName = path

  /**
   * The remote endpoint would have the compiled ejs, or what ever form of templates
   */
  const template = await getTemplateFromRemote(templateName)

  return Promise.resolve(template)
}
```

Let me know if you have any further questions.
