### ISSUE TITLE
Asset fragment in head is being ignored

### ISSUE THREAD

**Issue by timsim00** [zalando/tailor#43]
I'm working on this [SPA example](https://github.com/timsim00/tailor/blob/master/examples/spa/templates/index.html) where I'm trying to follow the pattern in your readme that shows an assets fragment in the head section.

`<head>
    <fragment src="http://assets.domain.com">
</head>`

But I'm showing that tailor is not trying to pull in my assets fragment.  

`Tailor started at port 8080
Fragment Header started at port 8081
Fragment Assets started at port 8082
/
/header.css
/header.css
/header.js`

I end up with this markup in the head section, which is there because of the fragment in the body to bring in the header.

`<script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="http://localhost:8081/header.js" src="http://localhost:8081/header.js"></script>`

**Comment by w0rm** [comment]
@timsim00 the assets fragment should be different, because it defines global dependencies for the page that should be executed before any fragment. 

Instead of specifying JavaScript from the HTTP Link header, you can return an inline script from the content of the assets fragment. In this script you require the global bundle and expose its internals as AMD modules. Something like this:

Fragment's content:

```html
<script>
(function (d) {
    require.config({waitSeconds: 0}); // disable timeout for requirejs if you need this
    require(d); // start fetching bundle.js
    var modules = ['module1', 'module2'];
    while (module = modules.pop()) {
        (function (dep) { 
            // make module1 and module2 available for other fragments on the page
            define(dep, d, function (b) {  
                return b[dep]; 
            });
        })(module);
    }
}(['http://localhost:8081/bundle.js']));
</script>
```

`bundle.js`:

```js
define(function () {
    return  {
        module1: function () { /* some useful code */ },
        module2: { foo : 'bar'}
    }
});
```
